expname: llff_fern
basedir: ./logs
datadir: ./data/nerf_llff_data/fern
dataset_type: llff

# network architecture
lr: 0.0005 # 5e-4
lr_decay: 250
chunk: 32768
netchunk: 65536

# setting
no_batching: False
no_reload: False
ft_path: 'None' # /data/silong/consistent_view_synthesis/nerf-pytorch/logs/orig/200000.tar
ckpt_dir: /data/silong/consistent_view_synthesis/nerf-pytorch/val_ckpt # /data/silong/consistent_view_synthesis/nerf-pytorch/logs

# rendering options
perturb: 1.0
use_viewdirs: True
i_embed: 0
multires: 10
multires_views: 4
raw_noise_std: 1
render_only: False
render_test: False
render_factor: 0
N_samples: 128
N_importance: 16
netdepth: 8
netwidth: 256
netdepth_fine: 8
netwidth_fine: 256


# training options
precrop_iters: 0
precrop_frac: 0.5
bs: 1024
hyper: 0.1

# dataset options
testskip: 8

## deepvoxels flags
shape: greek

## blender flags
white_bkgd: False
half_res: False

## llff flags
factor: 8
llffhold: 8
no_ndc: False
lindisp: False
spherify: False

# logging/saving options
i_print: 100
i_img: 1000
i_weights: 40000
i_testset: 50000
i_video: 50000


# model params
model:
  N_samples: ${N_samples}
  hidden_size: 64
  num_attention_heads: 2
  num_layers: 2

  netdepth: 8
  netwidth: 256
  multires: ${multires}

# optimizer
optim_name: adamw
scheduler: warmup_cosine
wd: 0.00001 # 1e-5
warmup_prop: 0.1
adam_epsilon: 0.00000001 # 1e-8
warmup_start_lr:


